# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
    form.type.datePicker:
        class: AppBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: datePicker }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
